version: "3.7"

services:

  # build outside like:  docker build -f ./ClientAPI/Dockerfile-alpine-non-root -t client-api:linux-arm64 --platform linux/arm64 .
  # or use image from local/external registry
  client-api:
    container_name: client-api
    image: client-api:linux-arm64
    environment:
      - NAMESPACE=demo
    ports:
      - "5199:8080"       # rootless, port 8080
      - "6199:3500"
      - "61990:50001"
      - "9999:9090"
  
  client-api-dapr:
    container_name: client-api-dapr
    image: daprio/daprd:1.10.0
    network_mode: "service:client-api"
    command: [ "./daprd",
               "-app-id", "client-api",
               "-dapr-http-port", "3500",
               "-dapr-grpc-port", "50001",
               "-metrics-port", "9090",
               "-app-port", "8080",         # rootless, port 8080
               "-placement-host-address", "dapr-placement:50006",
               "-components-path", "/components",
               "-config", "/configuration/dapr-config.yaml"
    ]
    volumes:
      - "./dapr/components/:/components"
      - "./dapr/configuration/:/configuration"
    depends_on:
      - client-api

  dapr-placement:
    image: daprio/dapr:1.11.0
    command: [ "./placement", "-port", "50006", "-log-level", "debug" ]
    ports:
      - "50006:50006"
