apiVersion: dapr.io/v1alpha1
kind: Configuration
metadata:
  name: config
spec:
  tracing:
    samplingRate: "1"
    zipkin:
      endpointAddress: "http://host.docker.internal:9411/api/v2/spans"
  metrics:
    enabled: true
  